name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2     
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-runtest@master
