name: Run tests

on: pull_request

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1.0.0      
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-runtest@master
