name: Run tests

on:
  push:
    branches: testing
  pull-request:
    branches: testing

jobs:
  test:
    runs-on: self-hosted
    #strategy:
    #  matrix:
    #    julia-version: ['1', '1.0']
    #    julia-arch: [x64, x86]
    #    os: [ubuntu-latest, windows-latest, macOS-latest]
    #    exclude:
    #      - os: macOS-latest
    #        julia-arch: x86

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
