name: Run tests

on: pull_request

jobs:
  unittests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2     
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-runtest@master
      - run: julia -e 'using Pkg; import Qaintessent; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    if: ${{ success() }}
